version: '3.5'
services:
  from-bakend:
      build: ./backend
      image: from-backend
      container_name: from-backend
      hostname: from-backend
      ports:
        - 16000:1000
      volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./backend:/api
          # แล้วแต่จะเพิ่ม
      restart: always
      stdin_open: true
      networks:
        - from-networks
  from-maria:
      image: mariadb:${MYSQL_TAG}
      container_name: from-maria
      hostname: from-maria
      volumes:
        - /etc/localtime:/etc/localtime:ro
        - ./dbs/mariadb:/var/lib/mysql
        #- ./50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      networks:
        - from-networks
  from-pma:
        image: phpmyadmin/phpmyadmin
        container_name: from-pma
        hostname: from-pma
        volumes:
          - /etc/localtime:/etc/localtime:ro
        ports:
          - 16001:80
        environment:
          - PMA_ARBITRARY=1
          - PMA_HOST=from-maria
          #- PMA_ABSOLUTE_URI=https://www.ai9.co.th/pma/
        restart: always
        links:
          - from-maria
        networks:
          - from-networks
networks:
    from-networks:
      external: true
      name: from-network





  